### ISSUE TITLE
Function httpParseInput() too restrictive

### ISSUE THREAD

**Issue by ddegorre-harmonicinc** [ChyroBroadcast/ftp-adm-api#2]
AngularJS send application/json;utf-8 header in $_SERVER['CONTENT_TYPE'] which is too restrictive with httpCheckOutputFormat() which parse $_SERVER['HTTP_ACCEPT'] .

**Comment by billy482** [comment]
Fixed in commit f3d8084a0c6eaff1a8183a8e7b726942fdca5af5
